### ISSUE TITLE
question about license

### ISSUE THREAD

**Issue by sunxinsara** [bcrypto/bee2evp#9]
The license says：

Bee2evp is released under the terms of the GNU General Public License version 3 (GNU GPLv3) with the **additional exemption that compiling, linking, and/or using OpenSSL is allowed**. See LICENSE for more information.

Does the "exemption" mean that my project's code can stay closed which linked to OpenSSL dynamic library that uses bee2evp engine?

**Comment by agievich** [comment]
The quoted phrase "with additional exemption that compiling, linking, and/or using OpenSSL is allowed" is extracted from the OpenSSL community guidelines (see https://www.openssl.org/docs/faq.html#LEGAL). This is exactly how they suggested defining the integrated OpenSSL + GPL licences.

According to http://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF, you can use the GPL plugin Bee2evp in a non-free program via OpenSSL without calling Bee2evp functions directly.

**Comment by agievich** [comment]
[Here](https://github.com/bcrypto/bee2evp/commit/896a749a5447c71344a201f19815ebe0ca4a4454) we clarify LICENSE to fully comply with the [dual OpenSSL and SSLeay license](https://www.openssl.org/source/license.html).

**Comment by sunxinsara** [comment]
Thank you very much for your reply
